server:
  port: 9999
spring:
  application:
    name: event-publisher
  cloud:
    stream:
      bindings:
        clientEvents-out-0:
          destination: click-events
      rabbit:
        bindings:
          clientEvents-out-0:
            producer:
              routing-key: "user.events.click"
management:
  tracing:
    sampling:
      probability: 1.0
    baggage:
      correlation:
        enabled: true
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        enabled: true
    tracing:
      endpoint: http://localhost:4318/v1/traces
      export:
        enabled: true