spring:
  application:
    name: user-service
  datasource:
    password: local
    username: local
    url: jdbc:postgresql://host.docker.internal:5432/local
    driver-class-name: org.postgresql.Driver
logging:
  level:
    io.micrometer.tracing: "debug"
    io.opentelemetry: "debug"
    org.personal.poc.events.observability.user: "debug"

management:
  tracing:
    sampling:
      probability: 1.0
    baggage:
      correlation:
        enabled: true
    propagation:
      type: W3C
  otlp:
    metrics:
      export:
        url: http://host.docker.internal:4318/v1/metrics
        enabled: true
    tracing:
      endpoint: http://host.docker.internal:4318/v1/traces
      export:
        enabled: true
    
