spring:
  application:
    name: user-service
  datasource:
    password: local
    username: local
    url: jdbc:postgresql://localhost:5432/local
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org.personal.poc.events.observability.user: "debug"

management:
  tracing:
    sampling:
      probability: 1.0
    baggage:
      correlation:
        enabled: true
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        enabled: true
    tracing:
      endpoint: http://localhost:4318/v1/traces
      export:
        enabled: true
