apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-publisher
  template:
    metadata:
      labels:
        app: event-publisher
    spec:
      containers:
      - name: event-publisher
        image: event-publisher:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: event-publisher-service
spec:
  selector:
    app:  event-publisher
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP 